name: sauce demo tests
on:
  push:
    branches:
      - "*"

env:
  USER_NAME: { { secrets.USER_NAME } }
  PASSWORD: { { secrets.PASSWORD } }


jobs:
  test_build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modules: [ 'LOGIN_SANITY', 'SANITY', 'PRODUCT' ]
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install playwright browsers
        run: python3 -m playwright install --with-deps
      - name: run playwright tests with pytest
        run: pytest -m ${{ matrix.modules }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report.html-${{ matrix.modules }}
          path: tests/
          retention-days: 30
